use-conda: true
latency-wait: 30
keep-going: true
printshellcmds: true
conda-frontend: conda
rerun-incomplete: true
default-storage-provider: gcs
rerun-trigger: [mtime, params, input]
storage-gcs-project: ${GOOGLE_PROJECT}
default-storage-prefix: ${WORKSPACE_BUCKET}/aryarm
