import warnings
from pathlib import Path
import snakemake.io as io
from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("9.23.0")


# if --configfile was not specified, import the default config file
if not ("modes" in config and "locus" in config and "snp_panel" in config):
    configfile: "config/config.yml"

def check_config(value, default=False, place=config, as_set=False):
    """return true if config value exists and is true"""
    value = place[value] if (value in place and place[value]) else default
    return (set(value) if isinstance(value, list) else {value}) if as_set else value

def gs_fix(og_value, tsfm_func):
    new_value = tsfm_func(og_value)
    if isinstance(og_value, snakemake.io._IOFile) and og_value.startswith(".snakemake/storage/gcs"):
        return og_value.new_from(new_value)
    return tsfm_func(new_value)


# handle defaults
config["out"] = check_config("out", "out")
config["min_maf"] = check_config("min_maf", 0)
mode = config["mode"]
# handle locus
if mode == "run":
    pheno_set = set(glob_wildcards(Path(config["modes"][mode]["pheno"])).trait)
if mode == "midway":
    locus = glob_wildcards(config["modes"][mode]["haps"]).locus
    if Path(config["locus"]).exists() and Path(config["locus"]).suffix == ".bed":
        with open(Path(config["locus"])) as f:
            # filter out loci that are not in the BED file
            regions = set(
                "\t".join(line.strip().split("\t")[:3]).replace("\t", "_", 1).replace("\t", "-", 1)
                for line in f
            )
            locus = [l for l in locus if l in regions]
elif Path(config["locus"]).exists() and Path(config["locus"]).suffix == ".bed":
    with open(Path(config["locus"])) as f:
        # the fourth column of the bed file must contain the name of the trait
        locus_file = [
            (cols[3], f"{cols[0]}_{float(cols[1]):.0f}-{float(cols[2]):.0f}")
            for cols in (line.strip().split() for line in f)
            if not cols[0].startswith("#") and (
                mode != "run" or (cols[3] in pheno_set)
            )
        ]
    locus_traits, locus = list(zip(*locus_file))
else:
    locus = config["locus"].replace(":", "_")
# remove any trailing slashes in directories
orig_out = str(Path(config["out"]))
config["out"] = str(Path(config["out"])) + "/{locus}"


module genotypes:
    snakefile: "rules/genotypes.smk"
    config: config

use rule * from genotypes as genotypes_*
if mode == "str":
    config["gts_str_panel"] = config["str_panel"]
if check_config("sample_size"):
    sampsize = config["sample_size"]
    config["gts_snp_panel"] = rules.genotypes_subset.output.pgen
    config["out"] += "/{sampsize}samples"
else:
    config["gts_snp_panel"] = rules.genotypes_subset.input.pgen
config["random"] = False

if mode == "ld_range" and check_config("num_haps", place=config["modes"][mode]):
    if isinstance(config["modes"][mode]["num_haps"], int):
        config["modes"][mode]["num_haps"] = [config["modes"][mode]["num_haps"],]

if mode == "midway":
    if not check_config("beta", place=config["modes"][mode]):
        # if no beta is specified, then we default to whatever is in the original hap
        # file (represented by a placeholder of 0)
        config["modes"][mode]["beta"] = (0,)
    if not check_config("reps", place=config["modes"][mode]):
        # if no reps are specified, then we default to just 1
        config["modes"][mode]["reps"] = 1

if mode != "run":
    module simulate:
        snakefile: "rules/simulate.smk"
        config: config
    use rule * from simulate as simulate_*

if mode == "ld_range" and config["modes"][mode]["random"]:
    config["random"] = True
    module simulate_random:
        snakefile: "rules/simulate.smk"
        config: config
    use rule * from simulate_random as simulate_random_*
del config["random"]

covar_file = check_config("covar", default=[])
if check_config("covar"):
    covar_config = {
        "covar": covar_file,
        "out": orig_out,
    }
    if mode == "run":
        covar_config["pheno"] = config["modes"][mode]["pheno"]
        if check_config("pheno_matrix", place=config["modes"][mode]):
            covar_config["pheno_matrix"] = config["modes"][mode]["pheno_matrix"]
    module covariates:
        snakefile: "rules/covariates.smk"
        config: covar_config
    use rule * from covariates as covariates_*
    if "pheno_matrix" in covar_config:
        covar_file = rules.covariates_merge.output.covar

if mode in ("str", "snp", "hap", "ld_range", "midway"):
    happler_config = {
        "pheno": rules.simulate_simphenotype.output.pheno,
        "hap_file": rules.simulate_transform.input.hap,
        "snp_panel": config["gts_snp_panel"],
        "out": config["out"] + "/happler/"+mode+"/beta_{beta}",
        "random": None,
        "covar": covar_file,
        "min_maf": check_config("min_maf", 0),
        "out_thresh": 1, # artificially set to 1 to avoid filtering
        "mode": mode,
    }
    if mode in ("hap", "ld_range", "midway"):
        happler_config["snps"] = []
        happler_config["causal_gt"] = rules.simulate_transform.output
        if mode == "hap":
            happler_config["snps"] = config["modes"][mode]["alleles"]
        elif mode == "ld_range":
            happler_config["out"] = config["out"] + "/happler/"+mode+"/{num_haps}_haps/ld_{ld}/beta_{beta}/alpha_{alpha}"
        elif mode == "midway":
            # happler_config["hap_file"] = rules.simulate_simphenotype.input.hap # do not uncomment!
            happler_config["out"] = config["out"] + "/midway/sim_{sim_mode}/beta_{beta}"
            happler_config["out_thresh"] = 1
    elif mode in ("str", "snp"):
        # also provide the SNP and STR IDs so that they can be used in the manhattan plot
        happler_config["snps"] = (config["modes"][mode]["id"],)
        # TODO: consider uncommenting this to compute LD with causal STR
        # if mode == "str":
        #     happler_config["causal_gt"] = config["gts_str_panel"]
    if check_config("reps", place=config["modes"][mode]):
        happler_config["out"] = happler_config["out"] + "/rep_{rep}"
elif mode == "run":
    happler_config = {
        "pheno": config["modes"][mode]["pheno"],
        "hap_file": [],
        "snp_panel": config["gts_snp_panel"],
        "out": config["out"] + f"/happler/{mode}/" + "{trait}",
        "random": None,
        "covar": covar_file,
        "min_maf": check_config("min_maf", 0),
        "out_thresh": check_config("out_thresh", 5e-8),
        "mode": mode,
    }
    if check_config("SVs", place=config["modes"][mode]):
        happler_config["SVs"] = config["modes"][mode]["SVs"]
else:
    raise ValueError("Unsupported operating 'mode' in config")


rule sub_pheno:
    """
    subset the phenotype file to include only the desired replicate
    """
    input:
        pheno=happler_config["pheno"],
    params:
        rep=lambda wildcards: int(wildcards.rep)+2,
    output:
        pheno=happler_config["out"] + "/phen.pheno",
    resources:
        runtime=7,
    threads: 1,
    log:
        happler_config["out"] + "/logs/sub_pheno",
    benchmark:
        happler_config["out"] + "/bench/sub_pheno",
    conda:
        "envs/default.yml"
    shell:
        "cut -f 1,{params.rep} {input.pheno} | "
        "(echo -e \"#IID\\thap\" && tail -n+2) >{output.pheno} 2>{log}"

happler_config["pheno"] = rules.sub_pheno.output.pheno if "{rep}" in happler_config["out"] else happler_config["pheno"]

rule sub_pheno_sort:
    """
    subset the phenotype file to include only the desired replicate
    """
    input:
        pheno=happler_config["pheno"],
        psam=Path(happler_config["snp_panel"]).with_suffix(".psam"),
    output:
        txt=happler_config["out"] + "/phen_sort.txt",
    resources:
        runtime=7,
    threads: 1,
    log:
        happler_config["out"] + "/logs/sub_pheno_sort",
    benchmark:
        happler_config["out"] + "/bench/sub_pheno_sort",
    conda:
        "envs/default.yml"
    shell:
        "comm -12 "
        "<(grep -Ev '^#' {input.psam} | cut -f1 | sort -u) "
        "<(grep -Ev '^#' {input.pheno} | cut -f1 | sort -u) >{output.txt} 2>{log}"

rule sub_pheno_split:
    """
    split the phenotype file into train and test splits using the former/latter X
    percent of the data where X is config["split"]
    """
    input:
        pheno=rules.sub_pheno.output.pheno,
        txt=rules.sub_pheno_sort.output.txt,
    params:
        split=lambda wildcards: check_config("split", default=1) if wildcards.split == "train" else (1 - check_config("split", default=0)),
        keep=lambda wildcards: "head" if wildcards.split == "train" else "tail",
    output:
        pheno=happler_config["out"] + "/phen.{split}.pheno",
    resources:
        runtime=7,
    threads: 1,
    log:
        happler_config["out"] + "/logs/sub_pheno_split.{split}",
    benchmark:
        happler_config["out"] + "/bench/sub_pheno_split.{split}",
    conda:
        "envs/default.yml"
    shell:
        "samp_count=\"$(wc -l <{input.txt})\" && "
        "cutoff=\"$(echo 'scale=0; ('\"$samp_count\"' * {params.split}) / 1' | bc)\" && "
        "( head -n1 {input.pheno} && "
        "shuf --random-source <(openssl enc -aes-256-ctr -pass pass:42 -nosalt < /dev/zero 2>/dev/null) {input.txt} | "
        "{params.keep} -n \"$cutoff\" | "
        "awk 'NR==FNR {{ids[$1]; next}} $1 in ids' - {input.pheno} | "
        "grep -F -x -f - {input.pheno}; ) > {output.pheno} 2>>{log}"

if check_config("split"):
    if mode == "midway":
        happler_config["pheno"] = expand(rules.sub_pheno_split.output.pheno, split="train", allow_missing=True)[0]


if mode == "midway":
    module midway:
        snakefile: "rules/midway.smk"
        config: happler_config
    use rule manhattan from midway as midway_manhattan
    happler_config["out"] = happler_config["out"] + "/{switch}"
    happler_config["midway_out"] = rules.midway_manhattan.output
    happler_config["pheno"] = expand(rules.sub_pheno_split.output.pheno, split="test", allow_missing=True)[0]

module happler:
    snakefile: "rules/happler.smk"
    config: happler_config
use rule * from happler as happler_*

if mode == "ld_range" and config["modes"][mode]["random"]:
    happler_config["random"] = rules.simulate_random_transform.output
    happler_config["random_hap"] = rules.simulate_random_transform.input.hap
    happler_config["out"] = config["out"] + "/happler/"+mode+"/random/{num_haps}_haps/ld_{ld}/beta_{beta}/alpha_{alpha}/rep_{rep}"
    module happler_random:
        snakefile: "rules/happler.smk"
        config: happler_config
    use rule * from happler_random as happler_random_*

if mode != "run":
    plots_config = {
        "out": config["out"] + "/plots",
        "mode": mode,
        "mode_attrs": config["modes"][mode],
        "causal_hap": rules.simulate_transform.input.hap if mode != "run" else [],
        "snp_panel": config["gts_snp_panel"],
        "sample_size": config["sample_size"],
    }
    if mode == "midway":
        plots_config["original_hap"] = plots_config["causal_hap"]
        plots_config["causal_hap"] = rules.midway_manhattan.output.hap
        plots_config["midway_linear"] = rules.midway_manhattan.output.linear
        plots_config["finemap_metrics"] = rules.happler_metrics.output.metrics
        plots_config["loci"] = locus
        plots_config["out"] = plots_config["out"].replace("/plots", "").replace("{locus}", "plots")
    else:
        if mode == "ld_range":
            plots_config["ld_range_checkpoint"] = checkpoints.simulate_create_hap_ld_range
        plots_config["happler_metrics"] = rules.happler_metrics.output.metrics
        plots_config["happler_hap"] = rules.happler_run.output.hap

    module plots:
        snakefile: "rules/plots.smk"
        config: plots_config
    use rule * from plots as plots_*

handle_gcs_storage = lambda i: storage(i) if i[0].startswith("gs://") else i

if mode == "ld_range":
    FINAL_OUTPUT = [rules.plots_params.output.png, rules.plots_metrics.output.png]
elif mode == "run":
    checkpoint multiline:
        """ obtain a list of the .hap files that have haplotypes with two or more alleles """
        input:
            hps = handle_gcs_storage(expand(
                rules.happler_run.output.hap.replace(".snakemake/storage/gcs", "gs:/"),
                zip, trait=locus_traits, locus=locus, allow_missing=True,
            )),
        params:
            out = lambda wildcards, output: str(output).replace("/multiline.tsv", ""),
            hp_path = Path(str(rules.happler_run.output.hap).format(locus="*", trait="*")),
        output:
            hps = orig_out + "/multiline.tsv",
        resources:
            runtime=10,
        log:
            orig_out + "/logs/multiline",
        benchmark:
            orig_out + "/bench/multiline",
        conda:
            "envs/default.yml"
        shell:
            "for i in {params.hp_path}; do if [ $("
            "grep '^V' $i | cut -f2 | sort | uniq -c | sed 's/^ *//' | awk -F ' ' '$1 > 1' | wc -l"
            ") -ne 0 ]; then echo $i; fi; done | "
            "sed 's+^{params.out}/++;s+/happler/run/+\\t+;s+/happler.hap$++' >{output} 2>{log}"

    def FINAL_OUTPUT(wildcards):
        files = [
            rules.happler_pips.output.tsv,
            rules.happler_tree.output.png,
            rules.happler_linreg.output.png,
            rules.happler_heatmap.output.png,
            # rules.happler_manhattan.output.png,
            rules.happler_cond_linreg.output.png,
            rules.happler_results.output.susie_pdf,
        ]
        if check_config("SVs", place=config["modes"][mode]):
            files.append(rules.happler_sv_ld.output.ld)
        with open(checkpoints.multiline.get().output["hps"], 'r') as file:
            hap_files = file.readlines()
            if not len(hap_files):
                # if there weren't any non-empty hap files, just return an empty list
                return []
            multiline_locus, multiline_traits = zip(*(f[:-1].split("\t") for f in hap_files))
        files = [ f.replace(".snakemake/storage/gcs", "gs:/") for f in files ]
        return handle_gcs_storage(expand(
            expand(
                files, zip, trait=multiline_traits, locus=multiline_locus,
                allow_missing=True,
            ), ex=("in","ex"), allow_missing=True,
        ))

    rule all:
        input:
            FINAL_OUTPUT
        default_target: True
elif mode == "midway":
    FINAL_OUTPUT = expand(
        expand(
            [
                rules.plots_midway.output.png,
                rules.plots_midway_metrics.output.png,
            ],
            switch=(
                # "bic",
                # "tscore",
                # "interact",
                # "covariance",
                # "interact-bic",
                "extension-bic",
                # "extension-tscore",
            ),
            allow_missing=True,
        ) + expand(
            [
                rules.plots_finemap.output.png,
                rules.plots_finemap_metrics.output.png,
            ],
            switch=("pip-parent", "pip-interact"),
            allow_missing=True,
        ) + expand(
            [
                rules.plots_finemap_cs_length.output.png,
            ],
            switch=("pip-parent"),
            allow_missing=True,
        ),
        sampsize=config["sample_size"],
    )
else:
    FINAL_OUTPUT = expand(
        [
            rules.happler_cond_linreg.output.png,
            rules.happler_tree.output.png,
            # rules.finemappers_results.output.susie_pdf,
            rules.happler_results.output.susie_pdf,
            # rules.plots_params.output.png,
        ],
        ex=(("in",) if mode == "hap" else ("ex", "in")),
        beta=config["modes"][mode]["beta"],
        allow_missing=True,
    )
    if check_config("reps", place=config["modes"][mode]):
        FINAL_OUTPUT = expand(
            FINAL_OUTPUT,
            rep=range(config["modes"][mode]["reps"]),
            allow_missing=True,
        )

# If '--config debug=true' is specified, we won't try to build the entire DAG
# This can be faster when you want to play around with a specific target output
if not check_config("debug", False) and mode != "run":
    rule all:
        input:
            expand(
                FINAL_OUTPUT,
                locus=locus,
                sampsize=config["sample_size"],
            ) if check_config("sample_size") else expand(FINAL_OUTPUT, locus=locus)
        default_target: True
