latency-wait: 30
use-conda: true
conda-frontend: conda
printshellcmds: true
shadow-prefix: /tscc/lustre/ddn/scratch/$USER

executor: slurm
default-resources:
    slurm_account: ddp268
    slurm_partition: condo
    runtime: 30
    nodes: 1
    slurm_extra: "'--qos=condo'"
