use-conda: true
latency-wait: 30
keep-going: true
scheduler: firstfit
printshellcmds: true
conda-frontend: conda
rerun-trigger: [mtime, params, input]
shadow-prefix: /tscc/lustre/ddn/scratch/$USER

executor: slurm
default-resources:
    slurm_account: htl149
    slurm_partition: hotel
    runtime: 30
    nodes: 1
    slurm_extra: "'--qos=hotel'"
